name: Dduels
version: '${version}'

main: org.starhc.dduels.Dduels
api-version: '1.21'
load: POSTWORLD
commands:
  duel:
    description: Main command.

  duelaccept:
    description: Command to accept duel.
    aliases:
      - accept
